### ISSUE TITLE
Supports hot reload

### ISSUE THREAD

**Issue by leegeunhyeok** [leegeunhyeok/react-native-esbuild#38]
# Description

Supports hot reload on development environment.

## Tasks

- [x] Implement custom file watcher instead esbuild.context.watch()
  - [x] On some files change, trigger rebuild() and get the metadata(path, etc..) of the changed module.
  - [x] Implement custom file system watcher using [chokidar](https://github.com/paulmillr/chokidar)
- [x] Transformer
  - [x] Skip if file is not changed (transform changed file only)
  - [x] Wrap modules with react-refresh context boundary
    - [x] Implement swc plugin (https://github.com/leegeunhyeok/swc-plugin-react-refresh)
  - [x] Custom module system
  - [x] Send HMR update message to client via web socket
  - [x] Evaluate updated code on client runtime
- [x] Get updated module code from bundle
- [x] Add experimental config for toggle hot reload

---

- [ ] #41

## References

- [react-refresh](https://www.npmjs.com/package/react-refresh)
- https://swc.rs/docs/configuration/compilation#jsctransformreactrefresh
- https://github.com/FredKSchott/esm-hmr/blob/master/src/client.ts
- PoC: https://github.com/leegeunhyeok/esbuild-hmr

## Limitations

- Esbuild isn't supports HMR(Hot Module Replacement).
- Cannot skip transform(js, ts) loader in Esbuild.

## Notes

- 0.1.0-alpha.42

---

```js
// before
var __commonJS = (cb, mod) => function __require2() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// after
global.cachedModule = {};
var __commonJS = (cb, mod) => {
  var name = __getOwnPropNames(cb)[0];
  Object.defineProperty(global.cachedModule, name, {
    get: () => mod
  });
  return function __require2() {
    return mod || (0, cb[name])((mod = { exports: {} }).exports, mod), mod.exports;
  };
};

// when file changes detected -> don't rebuild, just transform target file with swc only.
// `import { a, b, c } from 'module-path';`

try {
  const { a, b, c } = global.cachedModule['module-path'];

  // ...
} catch (error) {
  // hot reload failed. fully reload instead
}
```

```ts
// Esbuild metafile
interface Metafile {
  // `inputs` key is module file path.
  inputs: Record<string, {
    byte: number;
    imports: {
      path: string; // eg. 'node_modules/react/cjs/index.js'
      original: string; // eg. 'react'
      kind: '...',
    }[];
  }>[],
  // ...
}

// {
//   react: 'node_modules/react/cjs/index.js',
//   '../components': 'src/components/index.ts',
// }
const mappedModules = metafile.inputs[changedFilePath]?.imports.reduce((prev, curr) => {
  return { ...prev, [curr.original]: curr.path };
}, {});

// Example usage
import { transform } from '@swc/core';

await transform(code, {
  jsc: {
    experimental: {
      plugins: [
        // https://github.com/leegeunhyeok/swc-plugin-react-native-esbuild-module
        ['react-native-esbuild-module-plugin', {
          alias: mappedModules ?? {},
        }],
      ],
    },
  },
});
```

**Comment by leegeunhyeok** [comment]
### Notes

`branch: feat/38-hot-module-replacement_poc2`

- Implement swc plugin for react-refresh
  - Register React components
  - Create signature when component is using hooks
- Finding updates
  - Enhance file system watcher
  - Enhance bundled module code (add boundary for search it)
- And.. many things

https://github.com/leegeunhyeok/react-native-esbuild/assets/26512984/8249589c-ceba-43d9-a8e3-aa9e49d830d2

**Comment by leegeunhyeok** [comment]
# Notes

**Reverse dependencies**

<img width="739" alt="image" src="https://github.com/leegeunhyeok/react-native-esbuild/assets/26512984/a7df98d6-97f3-48ff-9436-626a7a71a57e">

<img width="1309" alt="image" src="https://github.com/leegeunhyeok/react-native-esbuild/assets/26512984/409e25de-3a8d-4cfb-a4a5-de45e038eab9">

<img width="538" alt="image" src="https://github.com/leegeunhyeok/react-native-esbuild/assets/26512984/9baec24e-c018-45d9-84cb-d8fa02426bde">


---

- Transform changed module only
- Send reverse dependencies information to client
  - accept changed module updates + accept on parent modules too

**Comment by leegeunhyeok** [comment]
Mistake > https://github.com/leegeunhyeok/react-native-esbuild/commit/de55ffb175d66437e18c8075122d94524eefdcb0

**Comment by leegeunhyeok** [comment]
### Notes

- `sideEffects: false` issue > (https://github.com/evanw/esbuild/issues/2795)

**Comment by benjamin7zero** [comment]
please bring HMR to this project, it would be crazy

**Comment by laogui** [comment]
I have been waiting
